name: release

on:
  push:
    branches:
      - master

jobs:
  generate:
    permissions: write-all
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build
        run: |
          platforms=("linux/amd64" "windows/amd64")
          for x in "${platforms[@]}"; do
            os=${x%%/*}
            arch=${x##*/}
            filename=${{ github.event.repository.name }}-$os-$arch
            if [ "$os" == "windows" ]; then
              filename+=".exe"
            fi
            GOOS=$os GOARCH=$arch CGO_ENABLED=0 go build -o dist/$filename
          done
      - name: Create a Release
        id: create_release
        uses: shogo82148/actions-create-release@v1

      - name: Upload Assets
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/*